#!/usr/bin/env python

import csv
import sys
import time
from Bio.Blast import NCBIWWW
from Bio.Blast import NCBIXML

#variables
dicoSNP = {}


#remplissage dicoSNP
#Lecture du fichier d'entree (.csv)
	# argument 1 = "Markers_position_16_Shiina.csv"
with open(sys.argv[1],"rb") as csvfileEntree:
	cr = csv.reader(csvfileEntree, delimiter = '\t', quotechar = '|')
	#creation dico clef = SNPname, valeur = sequence
	for row in cr:
		dicoSNP[row[0]]= row[1]
	#print dicoSNP
		#attention pas le meme ordre que dans table csv


def getSeqFlan5(n):
	return dicoSNP.get(dicoSNP.keys()[n])[0:100]


def getSeqFlan3(n):
	return dicoSNP.get(dicoSNP.keys()[n])[105:205]


def makeBlast():
	debut1=time.time()
	save_file = open("my_blast_all.xml", "w")
	for cle, valeur in dicoSNP.items():
		print "lance blast {} du {}:".format(dicoSNP.keys().index(cle), cle)
		debut = time.time()
		#voir pour le faire sur les deux sequences flanquante en meme temps
		#result_handle= NCBIWWW.qblast("blastn", "refseq_genomic",sequence="{}".format(getSeqFlan5(dicoSNP.keys().index(cle))), entrez_query="NC_006103.4[RefSeq]", format_type='Text')
		result_handle= NCBIWWW.qblast("blastn", "nt",sequence="{}".format(getSeqFlan5(dicoSNP.keys().index(cle))), entrez_query="NC_006103.4[accession]", format_type='xml')
		print "blast fini \t"
		fin = time.time()
		print "il a mis :", fin-debut
		#save_file = open("my_blast", "w")#pb j'ecrit un fichier a chaque fois / but : mettre tout dans le meme 
		save_file.write(result_handle.read())
		#save_file.write("\n\n\n\t\t\t ###################Alignement suivant###################  \n\n\n")
		#save_file.close()
	fin1=time.time()
	print "le temps total est de :", fin1-debut1
	save_file.close()



makeBlast()


#Recuperation des donnees de l'output blast.
	#attention un fichier global n'est peutpas une bonne solution (va recuperer seulement la position du premier alignement)

#je lui donne en argument le fichier?
def getBlastInfo ():
	save_file = open("my_blast_all.xml")
	#Si qu'une sequence blast il suffi de faier un .read
	blast.record = NCBIXML.read(save_file)
	#Sinon utiliser une for-loop avec un .parse
	blast.record = NCBIXML.parse(save_file)
	for blast_record in blast_records:
		#iterations sur le nombre de blast effectue
		for alignment in blast_record.alignments:
			for hsp in alignment.hsps:
				if hsp.expect < 0.04:
					#des print pour le moment
					#remplissag de nouveau dico ensuite
					print('*****Alignement*****')
					print('sequence :' alignment.title)
					print('taille alignement :' alignment.length)
					print('e-value :' hsp.expect)
					print('strand :' hsp.strand)
					print('debut query:' hsp.query_start)
					print('fin query:' hsp.query_end)
					print('debut sbjct:' hsp.sbjct_start)
					print('fin sbjct:' hsp.sbjct_end)
					print(hsp.query[0:alignment.length])
					print(hsp.match[0:alignment.length])
					print(hsp.sbjct[0:alignment.length])


getBlastInfo()







